version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DB_ENGINE=django.db.backends.sqlite3
      - DB_NAME=/app/db.sqlite3

  db:
    image: busybox
    volumes:
      - ./data/db.sqlite3:/app/db.sqlite3